#+title: Web Gallery of Art (WGA) unofficial Emacs Plugin

** Introduction
A small program to allow quick search in the art catalog of the Web Gallery of Art (WGA).

The program allows user to search and choose from the whole list of art pieces by and the title and the author's name.
Users are recommended to use a completion interface like `ivy' to achieve fuzzy search.
Then the chosen item can be either opened in browser (to the WGA page) or inserted as a link in Org Mode.
These correspond to two commands: `wga-open-in-browser' and `wga-insert-link-in-org-mode'.

** Target users
Emacsers who'd like to quickly refer to an art piece in their Org Mode notes, or simply to fuzzy search and browse an art piece on WGA.

** Disclaimer
This program is part of WGA.
The data associated with this program comes from WGA.

** Known issue
The data are lazy loaded but slow - it will take around half a minute when a `wga-*' command is triggered for the first time in an Emacs instance.
There's no performance issue after the first command.
PR is welcomed to improve this!
